version: '3'

services:
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_HOST: finallaravel.cd9rpruuw661.us-east-1.rds.amazonaws.com
    ports:
      - "8090:80"

  myapp:
    tty: true
    image: docker.io/bitnami/laravel:7-debian-10
    environment:
      - DB_HOST=finallaravel.cd9rpruuw661.us-east-1.rds.amazonaws.com
      - DB_USERNAME=admin
      - DB_DATABASE=finalLaravel
      - DB_PASSWORD=1qaz!QAZ
    ports:
      - 3300:3000
    volumes:
      - ./:/app
